# Example configuration file for LocAgent Kernel

# Agent configuration
agent:
  model_name: "gpt-4"
  temperature: 0.1
  max_tokens: 2048
  # OpenAI API configuration
  api_key: null  # Set via environment variable OPENAI_API_KEY or pass as parameter
  api_base: "https://api.openai.com/v1"  # Default OpenAI endpoint
  # For custom endpoints (e.g., Azure OpenAI):
  # api_base: "https://your-resource.openai.azure.com/openai/deployments/your-deployment"
  max_iterations: 10
  timeout: 300
  use_function_calling: true
  max_retries: 3
  retry_delay: 1.0

# Graph construction configuration
graph:
  node_types:
    - "directory"
    - "file" 
    - "class"
    - "function"
  
  edge_types:
    - "contains"
    - "inherits"
    - "invokes"
    - "imports"
  
  skip_dirs:
    - ".git"
    - ".github"
    - "__pycache__"
    - ".pytest_cache"
    - "node_modules"
    - "venv"
    - ".venv"
    - "env"
    - ".env"
  
  file_extensions:
    - ".py"
    - ".js"
    - ".ts"
    - ".java"
    - ".cpp"
    - ".c"
    - ".h"
  
  max_depth: 10

# Retrieval configuration
retrieval:
  bm25_k1: 1.2
  bm25_b: 0.75
  top_k: 10
  fuzzy_threshold: 0.8
  cache_dir: null  # Will use default cache location

# General configuration
work_dir: "."
log_level: "INFO"
log_file: null
num_processes: 1
batch_size: 10